name: del runs and releases
on:
  schedule:
    - cron: '55 17 4/15 * *' # Runs at 01:55 UTC+8 on the 5 and 20th of every month.
  workflow_dispatch:
    inputs:
      retain_days:
        description: 'Retain days:'
        required: true
        default: 31

env:
  TZ: Asia/Shanghai
  DEBIAN_FRONTEND: noninteractive
  RETAIN_DAYS: ${{ github.event.inputs.retain_days }}

jobs:
  del_runs_and_releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete outdate workflow runs
        uses: actions/github-script@v6
        with:
          script: |
            const del_outdate_runs = require('./scripts/del-outdate-runs');
            del_outdate_runs({ github, context });

      - name: Delete outdate releases
        uses: actions/github-script@v6
        with:
          script: |
            const del_outdate_releases = require('./scripts/del-outdate-releases');
            del_outdate_releases({ github, context });
