name: openwrt-19.07-arm64-n1

on:
  schedule:
    - cron: 0 2 1 */2 *

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout configs
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/configs

      - name: Checkout openwrt repo
        uses: actions/checkout@v2
        with:
          repository: Lienol/openwrt
          path: ${{ github.workspace }}/openwrt
          ref: dev-19.07

      - name: Checkout n1 maker repo
        uses: actions/checkout@v2
        with:
          repository: tuanqing/mknop
          path: ${{ github.workspace }}/mknop

      - name: Workspace init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android /usr/lib/jvm /opt/ghc
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Feeds init
        run: |
          cat $GITHUB_WORKSPACE/configs/openwrt-19.07.feeds > $GITHUB_WORKSPACE/openwrt/feeds.conf.default
          cat $GITHUB_WORKSPACE/openwrt/feeds.conf.default
          cd $GITHUB_WORKSPACE/openwrt
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/parted package/parted
          git clone https://github.com/tuanqing/install-program package/install-program
          ./scripts/feeds update -a && ./scripts/feeds install -a
          cat >> $GITHUB_WORKSPACE/openwrt/feeds/luci/themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css << EOF
          #cbi-passwall-acl_rule .cbi-dropdown:not(.btn):not(.cbi-button),#cbi-passwall-acl_rule .cbi-dynlist{min-width:unset;}
          #list-content table{width:100%;}#list-content table tr td{height:30px;line-height:30px;}
          EOF

      - name: Make defconfig
        run: |
          rm -f $GITHUB_WORKSPACE/openwrt/.config
          cp $GITHUB_WORKSPACE/configs/openwrt-19.07-arm64-n1.config $GITHUB_WORKSPACE/openwrt/.config
          cd $GITHUB_WORKSPACE/openwrt/
          make defconfig

      - name: Make download
        run: |
          cd $GITHUB_WORKSPACE/openwrt/
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Multi-thread compile
        run: |
          cd $GITHUB_WORKSPACE/openwrt/
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s

      - name: Single-thread compile
        if: failure()
        run: |
          cd $GITHUB_WORKSPACE/openwrt/
          make -j1 V=s

      - name: Make n1 firmware
        if: success()
        run: |
          find $GITHUB_WORKSPACE/openwrt/bin/targets/ -name "*rootfs.tar.gz" | xargs -i mv -f {} $GITHUB_WORKSPACE/mknop/openwrt/
          cd $GITHUB_WORKSPACE/mknop/
          sudo ./make -d -s 512 -k 5.4.43
          cd $GITHUB_WORKSPACE/mknop/out
          tar -zcvf openwrt-firmware-n1.tar.gz ./*
          ls -la ./

      - name: Upload targets
        if: success()
        uses: actions/upload-artifact@master
        with:
          name: openwrt-19.07-arm64-n1
          path: ${{ github.workspace }}/mknop/out/openwrt-firmware-n1.tar.gz
