name: openwrt-21.02-aarch64

on:
  schedule:
    - cron: '0 18 4/15 * *' # Runs at 02:00 UTC+8 on the 5 and 20th of every month.
  workflow_dispatch:
  repository_dispatch:
    types: 'run-build-op-aarch64'

env:
  TZ: Asia/Shanghai
  DEBIAN_FRONTEND: noninteractive

jobs:
  build-openwrt:
    runs-on: ubuntu-20.04
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event.action == 'run-build-op-aarch64'
    steps:
      - uses: actions/checkout@v2

      - name: Workspace init
        run: |
          echo "DISTRO_VERSION=$(date +'v%y.%m.%d')" >> $GITHUB_ENV
          sudo bash $GITHUB_WORKSPACE/scripts/init-workspace.bash
          sudo -E apt-get -qq install mount util-linux uuid-runtime fdisk parted dosfstools e2fsprogs btrfs-progs

      - name: 1-1 Multi-thread compile [aarch64]
        if: success()
        run: |
          cd $GITHUB_WORKSPACE/
          git apply --check configs/diffs/aarch64-n1.diff
          git apply configs/diffs/aarch64-n1.diff
          mkdir -p $GITHUB_WORKSPACE/out/
          bash $GITHUB_WORKSPACE/scripts/prebuild.bash
          cd $GITHUB_WORKSPACE/openwrt/
          make -j $(($(nproc)+1)) V=s

      - name: 1-2 Single-thread compile [aarch64]
        if: failure()
        run: |
          cd $GITHUB_WORKSPACE/openwrt/
          make -j 1 V=s

      - name: 2 Pack up targets [aarch64]
        if: success()
        run: |
          find $GITHUB_WORKSPACE/openwrt/bin/targets/ -name "openwrt-armvirt-64-default-rootfs.tar.gz" | xargs -i mv -f {} $GITHUB_WORKSPACE/out/openwrt-armvirt-64-default-rootfs.tar.gz
          tree $GITHUB_WORKSPACE/out/

      - name: 3 Package firmware [firmware]
        if: success()
        uses: unifreq/openwrt_packit@master
        env:
          WHOAMI: Rookie_Zoe
          GZIP_IMGS: .gz
          OPENWRT_VER: ${{ env.DISTRO_VERSION }}
          PACKAGE_SOC: s905d
          OPENWRT_ARMVIRT: out/openwrt-armvirt-64-default-rootfs.tar.gz
          KERNEL_VERSION_NAME: 5.4.185

      - name: 4-1 Upload targets [aarch64]
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: openwrt-armvirt-64-default-rootfs.tar.gz
          path: ${{ github.workspace }}/out/openwrt-armvirt-64-default-rootfs.tar.gz

      - name: 4-2 Prepare targets [firmware]
        run: |
          tree ${{ env.PACKAGED_OUTPUTPATH }}/
          cd ${{ env.PACKAGED_OUTPUTPATH }}/
          find ./ -follow -type f -name "openwrt_*.img" -print | while read -r img; do
            gzip "$img"
          done
          tree ${{ env.PACKAGED_OUTPUTPATH }}/

      - name: 5-1 Upload firmware to release
        if: success()
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.DISTRO_VERSION }}
          name: ${{ env.DISTRO_VERSION }}
          body: |
            Auto released by actions
            Now is ${{ env.DISTRO_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          replacesArtifacts: true

      - name: 5-2 Upload targets [firmware]
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: openwrt-armvirt-64-${{ env.DISTRO_VERSION }}
          path: ${{ env.PACKAGED_OUTPUTPATH }}/*
