name: openwrt-21.02-aarch64

on:
  schedule:
    - cron: '0 18 4/15 * *' # Runs at 02:00 UTC+8 on the 5 and 20th of every month.
  workflow_dispatch:
  repository_dispatch:
    types: 'run-build-op-aarch64'

env:
  TZ: Asia/Shanghai

jobs:
  build-openwrt:
    runs-on: ubuntu-18.04
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event.action == 'run-build-op'
    steps:
      - uses: actions/checkout@v2

      - name: Workspace init
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android /usr/lib/jvm /opt/ghc
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf tree curl
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: 1 Multi-thread compile [aarch64]
        if: success()
        run: |
          cd $GITHUB_WORKSPACE/
          git apply --check configs/diffs/aarch64-n1.diff
          git apply configs/diffs/aarch64-n1.diff
          mkdir -p $GITHUB_WORKSPACE/out/
          bash $GITHUB_WORKSPACE/prebuild.bash
          cd $GITHUB_WORKSPACE/openwrt/
          make -j $(($(nproc)+1)) V=s

      - name: 1-2 Single-thread compile [aarch64]
        if: failure()
        run: |
          cd $GITHUB_WORKSPACE/openwrt/
          make -j 1 V=s

      - name: 2 Pack up targets [aarch64]
        if: success()
        run: |
          echo "DISTRO_VERSION=$(date +'v%y.%m.%d')" >> $GITHUB_ENV
          find $GITHUB_WORKSPACE/openwrt/bin/targets/ -name "openwrt-armvirt-64-default-rootfs.tar.gz" | xargs -i mv -f {} $GITHUB_WORKSPACE/out/openwrt-armvirt-64-default-rootfs.tar.gz

      - name: 3 Package firmware [firmware]
        if: success()
        uses: unifreq/openwrt_packit@master
        env:
          WHOAMI: Rookie_Zoe
          OPENWRT_VER: ${{ env.DISTRO_VERSION }}
          PACKAGE_SOC: s905d
          OPENWRT_ARMVIRT: out/openwrt-armvirt-64-default-rootfs.tar.gz
          KERNEL_VERSION_NAME: 5.4.184

      - name: 4 Upload targets [aarch64]
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: openwrt-armvirt-64-default-rootfs.tar.gz
          path: ${{ github.workspace }}/out/openwrt-armvirt-64-default-rootfs.tar.gz

      - name: 4 Prepare targets [firmware]
        run: |
          cd ${{ env.PACKAGED_OUTPUTPATH }}/
          find ./ -follow -type f -name "openwrt_*.img" -print | while read -r img; do
            gzip "$img"
          done
          tree ${{ env.PACKAGED_OUTPUTPATH }}/

      - name: 5 Upload firmware to release
        if: success()
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.DISTRO_VERSION }}
          name: ${{ env.DISTRO_VERSION }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Auto released by actions
